    /* ---------- persistence ---------- */
    function devApply ( save )
    {
      if ( save !== false ) { clearTimeout( saveT ); saveT = setTimeout( () => { try { localStorage.setItem( DRAFT_KEY, JSON.stringify( MAPD ) ); } catch ( e ) { } }, 250 ); }
      syncWorld(); setHover( null ); hvPrev = null; if ( !gs ) pruneSel(); refreshSelUI();
      devStatus(); if ( $( 'devLibrary' ).classList.contains( 'open' ) ) renderPlaced();
    }
    function devStatus () { const e = $( 'devSt' ); if ( e ) e.textContent = 'Added: ' + MAPD.added.length + ' · Removed: ' + MAPD.removed.length; const u = $( 'devUndo' ), r = $( 'devRedo' ); if ( u ) { u.disabled = !undoS.length; r.disabled = !redoS.length; } }
    function warmEditorShaders ()
    {
      const materials = new Set(), samples = [];
      scene.traverse( o =>
      {
        if ( !o.isMesh ) return;
        let parent = o; while ( parent && parent !== tc ) parent = parent.parent; if ( parent === tc ) return;
        if ( o.isTransformControlsPlane ) return;
        const source = Array.isArray( o.material ) ? o.material : [ o.material ];
        source.forEach( mat =>
        {
          if ( !mat || materials.has( mat ) ) return; materials.add( mat );
          const sample = o.clone( false ); sample.material = mat; sample.visible = true; sample.frustumCulled = false;
          samples.push( ghostify( sample ) );
        } );
      } );
      samples.forEach( sample => scene.add( sample ) ); if ( tc ) scene.remove( tc );
      try { scene.updateMatrixWorld( true ); camera.updateMatrixWorld( true ); renderer.compile( scene, camera ); }
      catch ( error ) { console.warn( 'Editor shader warmup skipped:', error ); }
      finally { samples.forEach( sample => scene.remove( sample ) ); if ( tc ) scene.add( tc ); }
    }
    warmEditorShaders(); setTimeout( warmAssetPrototypes, 1200 );
    function devExport ()
    {
      const data = { version: Date.now(), removed: MAPD.removed, added: MAPD.added };
      const txt = '/* generated by dev.html - upload next to index.html */\nwindow.MAP_DATA = ' + JSON.stringify( data, null, 2 ) + ';\n';
      const a = document.createElement( 'a' ); a.href = URL.createObjectURL( new Blob( [ txt ], { type: 'text/javascript' } ) ); a.download = 'map-data.js'; a.click();
    }
