/* node build.js  ->  writes world-3d.js (the same program as src/, as ONE file) for pages that load a single script. */
const fs = require( 'fs' ), path = require( 'path' );
const { assemble } = require( './src/loader.js' );
const dir = path.join( __dirname, 'src' ), manifest = JSON.parse( fs.readFileSync( path.join( dir, 'manifest.json' ), 'utf8' ) );
const code = assemble( p => fs.readFileSync( path.join( dir, p ), 'utf8' ), manifest, 'src/', false );
fs.writeFileSync( path.join( __dirname, 'world-3d.js' ), '/* GENERATED by build.js from src/ - edit the files in src/, not this one. */\n' + code );
console.log( 'world-3d.js written (' + manifest.parts.filter( p => p[ 0 ] !== '#' ).length + ' files, ' + code.split( '\n' ).length + ' lines)' );
